Repository uoslife/client-meeting-season3, pull requests merged in 2023-05, with the labels that each got.

#35 Feat/12 group structure
  public/images/icons/Person.svg
  public/images/icons/User.svg
  src/app/apply/group/page.tsx
  src/components/buttons/checkCircle/CheckCircle.style.tsx
  src/components/buttons/checkCircle/CheckCircle.tsx
  src/components/buttons/deleteButton/DeleteButton.tsx
  src/components/buttons/iconButton/IconButton.tsx
  src/components/buttons/roundedRectangleButton/RoundedRectangleButton.style.tsx
  src/components/buttons/roundedRectangleButton/RoundedRectangleButton.tsx
  src/components/index.ts
  src/components/input/droptdownInput/DropdownInput.style.tsx
  src/components/input/droptdownInput/DropdownInput.tsx
  src/components/input/textRoundInput/TextRoundInput.style.tsx
  src/components/input/textRoundInput/TextRoundInput.tsx
  src/components/layout/Paddle.tsx
  src/components/layout/Row.tsx
  src/components/modal/bottomSheet/BottomSheet.style.tsx
  src/components/modal/bottomSheet/BottomSheet.tsx
  src/components/typography/text/Text.tsx
  src/hooks/useInput.ts
  src/pages/group/FirstStep/FirstPage.tsx
  src/pages/group/FirstStep/SecondPage.tsx
  src/pages/group/FirstStep/SecondPage/GroupLeaderPage/GroupLeaderPage.style.tsx
  src/pages/group/FirstStep/SecondPage/GroupLeaderPage/GroupLeaderPage.tsx
  src/pages/group/FirstStep/SecondPage/GroupMemberPage/GroupMemberPage.style.tsx
  src/pages/group/FirstStep/SecondPage/GroupMemberPage/GroupMemberPage.tsx
  src/pages/group/FirstStep/SecondPage/SecondPage.tsx
  src/pages/group/FirstStep/index.tsx
  src/pages/group/SecondStep/FifthPage.tsx
  src/pages/group/SecondStep/FirstPage.tsx
  src/pages/group/SecondStep/FourthPage.tsx
  src/pages/group/SecondStep/SecondPage.tsx
  src/pages/group/SecondStep/SixthPage.tsx
  src/pages/group/SecondStep/ThirdPage.tsx
  src/pages/group/SecondStep/index.tsx
  src/pages/group/ThirdStep/FirstPage.tsx
  src/pages/group/ThirdStep/SecondPage.tsx
  src/pages/group/ThirdStep/ThirdPage.tsx
  src/pages/group/ThirdStep/index.tsx
Labels: 미팅

#34 feat: 신청 완료 페이지 제작
  src/app/apply/finish/page.tsx
  src/components/layout/Paddle.tsx
Labels: 공통

#38 Feat/group choice page - #32
  src/app/apply/branching/page.tsx
  src/app/apply/page.tsx
  src/app/apply/personal/page.tsx
  src/app/apply/template.tsx
  src/app/page.tsx
  src/components/footer/Footer.tsx
  src/components/header/progressHeader/ProgressHeader.tsx
  src/pages/common/LastStep.tsx
  src/store/feature/applyInfo.ts
Labels: 개선, 미팅, 공통

#40 Feat/improve complete page - #37
  src/app/apply/complete/page.tsx
  src/app/apply/group/page.tsx
  src/app/apply/template.tsx
  src/components/footer/Footer.tsx
Labels: 개선, 공통

#41 feat: Button 컴포넌트 textSize props 추가 - #39
  src/app/apply/branching/page.tsx
  src/app/apply/complete/page.tsx
  src/app/apply/page.tsx
  src/components/buttons/button/Button.tsx
Labels: 개선, 공통

#46 Feat/44-select-department
  src/components/buttons/roundedRectangleButton/RoundedRectangleButton.style.tsx
  src/components/buttons/roundedRectangleButton/RoundedRectangleButton.tsx
  src/components/index.ts
  src/components/input/textRoundInput/TextRoundInput.tsx
  src/components/layout/Row.tsx
  src/components/molecules/departmentSelectBox/DepartmentSelectBox.style.tsx
  src/components/molecules/departmentSelectBox/DepartmentSelectBox.tsx
  src/constants/departments.ts
  src/hooks/useInput.ts
Labels: 공통

#59 feat: 동물상 컴포넌트 작성 - #54
  public/images/animals/1.svg
  public/images/animals/2.svg
  public/images/animals/3.svg
  public/images/animals/4.svg
  public/images/animals/5.svg
  public/images/animals/6.svg
  public/images/animals/7.svg
  public/images/animals/8.svg
  public/images/animals/9.svg
  src/components/buttons/animalButton/AnimalButton.style.tsx
  src/components/buttons/animalButton/AnimalButton.tsx
  src/components/buttons/checkbox/Checkbox.tsx
  src/components/index.ts
Labels: 공통

#63 feat: 3대3미팅 팅장, 팅원 신청 페이지 directory 구분 - #42
  src/app/apply/groupMember/GroupMemberPage.style.tsx
  src/app/apply/groupMember/page.tsx
  src/pages/groupLeader/FirstStep/SecondPage.tsx
  src/pages/groupLeader/FirstStep/SecondPage/GroupLeaderPage.style.tsx
  src/pages/groupLeader/FirstStep/SecondPage/SecondPage.tsx
  src/pages/groupLeader/FirstStep/SecondPage/index.tsx
  src/pages/groupLeader/FirstStep/index.tsx
Labels: 개선, 미팅

#50 Feat/49-dropdown-input-component
  src/components/buttons/deleteButton/DeleteButton.tsx
  src/components/input/droptdownInput/DropdownInput.style.tsx
  src/components/input/droptdownInput/DropdownInput.tsx
Labels: 개선, 공통

#73 Feat/30-personal-secondStep
  src/page/personal/FirstStep/FirstPage.tsx
  src/page/personal/FirstStep/FourthPage.tsx
  src/page/personal/FirstStep/SecondPage.tsx
  src/page/personal/FirstStep/ThirdPage.tsx
  src/page/personal/SecondStep/FirstPage.tsx
  src/page/personal/SecondStep/FourthPage.tsx
  src/page/personal/SecondStep/SecondPage.tsx
  src/page/personal/SecondStep/ThirdPage.tsx
Labels: 소개팅

#75 Feat/69 interest select component
  public/images/interests/1.svg
  public/images/interests/10.svg
  public/images/interests/2.svg
  public/images/interests/3.svg
  public/images/interests/4.svg
  public/images/interests/5.svg
  public/images/interests/6.svg
  public/images/interests/7.svg
  public/images/interests/8.svg
  public/images/interests/9.svg
  src/components/buttons/interstSelectButton/InterestSelectButton.style.tsx
  src/components/buttons/interstSelectButton/InterestSelectButton.tsx
  src/components/index.ts
  src/constants/index.ts
  src/page/personal/FirstStep/FifthPage.tsx
Labels: 소개팅

#64 Feat/53-mbti-button-component
  src/components/buttons/button/Button.style.tsx
  src/components/buttons/button/Button.tsx
  src/components/index.ts
  src/components/molecules/mbtiSelectBox/MbtiButton.tsx
  src/components/molecules/resultBox/ResultBox.tsx
  src/constants/index.ts
  src/page/personal/ThirdStep/FourthPage.tsx
Labels: 소개팅

#77 feat:group state management - #56
  src/app/apply/groupLeader/page.tsx
  src/app/apply/groupMember/page.tsx
  src/app/apply/template.tsx
  src/components/buttons/button/Button.tsx
  src/components/footer/Footer.tsx
  src/components/header/progressHeader/ProgressHeader.tsx
  src/constants/index.ts
  src/hooks/useClickButton.ts
  src/hooks/useCurPageReset.ts
  src/page/common/applyMyInfoStep/FirstPage.tsx
  src/page/common/applyMyInfoStep/SecondPage.tsx
  src/page/groupLeader/FirstStep/FirstPage.tsx
  src/page/groupLeader/FirstStep/SecondPage.tsx
  src/page/groupLeader/FirstStep/index.tsx
  src/page/groupLeader/FourthStep/FirstPage.tsx
  src/page/groupLeader/FourthStep/index.tsx
  src/page/groupLeader/SecondStep/FifthPage.tsx
  src/page/groupLeader/SecondStep/FirstPage.tsx
  src/page/groupLeader/SecondStep/FourthPage.tsx
  src/page/groupLeader/SecondStep/SecondPage.tsx
  src/page/groupLeader/SecondStep/SixthPage.tsx
  src/page/groupLeader/SecondStep/ThirdPage.tsx
  src/page/groupLeader/SecondStep/index.tsx
  src/page/groupLeader/ThirdStep/FifthPage.tsx
  src/page/groupLeader/ThirdStep/FirstPage.tsx
  src/page/groupLeader/ThirdStep/FourthPage.tsx
  src/page/groupLeader/ThirdStep/SecondPage.tsx
  src/page/groupLeader/ThirdStep/ThirdPage.tsx
  src/page/groupLeader/ThirdStep/index.tsx
  src/page/groupMember/FirstStep/FirstPage.tsx
  src/page/groupMember/FirstStep/index.tsx
Labels: 개선, 미팅

#84 feat: group state management - #56
  src/app/apply/groupLeader/page.tsx
  src/app/apply/groupMember/page.tsx
  src/components/header/progressHeader/ProgressHeader.tsx
  src/components/index.ts
  src/components/input/dropdownInput/DropdownInput.style.tsx
  src/components/input/dropdownInput/DropdownInput.tsx
  src/components/molecules/departmentSelectBox/DepartmentSelectBox.tsx
  src/constants/index.ts
  src/page/common/ConfirmStep.tsx
  src/page/common/applyMyInfoStep/index.tsx
  src/page/groupLeader/FourthStep/FirstPage.tsx
  src/page/groupLeader/FourthStep/index.tsx
  src/page/groupMember/SecondStep/FirstPage.tsx
  src/page/groupMember/SecondStep/index.tsx
Labels: 개선, 미팅, 공통

#82 feat: 신청 완료 페이지 lottie animation 추가
  package.json
  src/app/apply/complete/page.tsx
  src/assets/lottie/congratulation.json
  yarn.lock
Labels: 공통

#88 feat: slider component 작성 - #51
  src/components/molecules/slider/Slider.style.tsx
  src/components/molecules/slider/Slider.tsx
Labels: 공통

#89 Feat/87-team-code-page
  src/page/groupMember/SecondStep/FirstPage.tsx
Labels: 개선, 미팅

#93 Feat/85 animal page
  src/components/buttons/animalButton/AnimalButton.tsx
  src/components/buttons/interstSelectButton/InterestSelectButton.style.tsx
  src/constants/index.ts
  src/hooks/useClickButton.ts
  src/page/personal/FirstStep/ThirdPage.tsx
  src/page/personal/ThirdStep/ThirdPage.tsx
Labels: 개선, 소개팅

#92 Feat/72-check-apply-information-page
  src/components/molecules/teamStatusBox/TeamStatusBox.tsx
  src/page/common/ConfirmStep.tsx
Labels: 공통

#94 Feat/90-department-select-box
  src/components/buttons/deleteButton/DeleteButton.tsx
  src/components/buttons/roundedRectangleButton/RoundedRectangleButton.style.tsx
  src/components/buttons/roundedRectangleButton/RoundedRectangleButton.tsx
  src/components/molecules/departmentSelectBox/DepartmentSelectBox.tsx
  src/page/groupLeader/FourthStep/FirstPage.tsx
Labels: 개선, 공통

#102 feat: 99-상대 선호 MBTI 복수 선택 수정
  src/components/molecules/mbtiSelectBox/MbtiButton.tsx
  src/page/personal/FirstStep/FourthPage.tsx
  src/page/personal/ThirdStep/FourthPage.tsx
Labels: 개선, 소개팅

#101 feat: 1대1 step3 page2 선호 상대 정보 입력하기 페이지 제작
  src/components/molecules/departmentSelectBox/DepartmentSelectBox.tsx
  src/page/personal/ThirdStep/SecondPage.tsx
Labels: 소개팅

#116 Feat/107 group global data control
  src/app/apply/complete/page.tsx
  src/components/molecules/resultBox/ResultBox.tsx
  src/hooks/useClickButton.ts
  src/page/common/ConfirmStep.tsx
  src/page/common/applyMyInfoStep/FirstPage.tsx
  src/page/common/applyMyInfoStep/SecondPage.tsx
  src/page/common/applyMyInfoStep/index.tsx
  src/page/groupLeader/FourthStep/FirstPage.tsx
  src/page/groupLeader/SecondStep/FirstPage.tsx
  src/page/groupLeader/ThirdStep/FifthPage.tsx
  src/page/groupLeader/ThirdStep/FirstPage.tsx
  src/page/groupLeader/ThirdStep/FourthPage.tsx
  src/page/groupLeader/ThirdStep/SecondPage.tsx
  src/page/groupLeader/ThirdStep/ThirdPage.tsx
  src/page/personal/FirstStep/FifthPage.tsx
  src/page/personal/FirstStep/FourthPage.tsx
  src/page/personal/FirstStep/ThirdPage.tsx
  src/page/personal/SecondStep/FirstPage.tsx
  src/page/personal/SecondStep/FourthPage.tsx
  src/page/personal/SecondStep/SecondPage.tsx
  src/page/personal/SecondStep/ThirdPage.tsx
  src/page/personal/ThirdStep/FirstPage.tsx
  src/page/personal/ThirdStep/FourthPage.tsx
  src/page/personal/ThirdStep/SecondPage.tsx
  src/page/personal/ThirdStep/ThirdPage.tsx
Labels: 개선, 공통

#114 fix: MainPoster jpg 변경
  public/images/MainPoster.jpg
  public/images/MainPoster.png
  src/app/page.tsx
Labels: 개선, 공통

#113 fix: 상대 mbti 선호 로직 설명 추가
  src/components/molecules/mbtiSelectBox/MbtiButton.tsx
  src/page/personal/ThirdStep/FourthPage.tsx
Labels: 개선, 공통

#117 feat: api setting - #111
  .gitignore
  next.config.js
  package.json
  src/api/core/index.ts
  src/api/index.ts
  src/api/services/Auth.type.ts
  src/api/services/AuthAPI.ts
  src/api/services/Meeting.type.ts
  src/api/services/MeetingAPI.ts
  src/api/services/types.ts
  src/api/types/auth.type.ts
  src/api/types/meeting.type.ts
  src/app/applicationInfo/page.tsx
  src/app/apply/branching/page.tsx
  src/app/apply/complete/page.tsx
  src/app/apply/page.tsx
  src/app/layout.tsx
  src/components/footer/Footer.tsx
  src/components/modal/bottomSheet/BottomSheet.style.tsx
  src/page/groupMember/SecondStep/FirstPage.tsx
  src/page/groupMember/SecondStep/index.tsx
  src/utils/context/formContext.ts
  src/utils/context/userIdContext.ts
  src/utils/native/actions.ts
  src/utils/native/bridge.ts
  src/utils/native/index.ts
  src/utils/native/tasks.ts
  yarn.lock
Labels: 개선, 소개팅, 미팅, 공통

#119 feat: mbti prefer order - #112
  src/app/page.tsx
  src/components/molecules/resultBox/ResultBox.tsx
  src/hooks/useClickButton.ts
  src/page/personal/ThirdStep/FourthPage.tsx
Labels: 소개팅

#126 fix: 노션 배포 전 ux 디자인 개선
  src/app/apply/complete/page.tsx
  src/app/page.tsx
  src/components/buttons/interstSelectButton/InterestSelectButton.tsx
  src/components/header/progressHeader/ProgressHeader.tsx
  src/components/modal/bottomSheet/BottomSheet.style.tsx
  src/components/molecules/resultBox/ResultBox.tsx
  src/constants/index.ts
  src/page/common/ConfirmStep.tsx
  src/page/groupLeader/SecondStep/SecondPage.tsx
  src/page/personal/FirstStep/FifthPage.tsx
  src/page/personal/FirstStep/FourthPage.tsx
  src/page/personal/ThirdStep/FirstPage.tsx
  src/page/personal/ThirdStep/FourthPage.tsx
  src/page/personal/ThirdStep/ThirdPage.tsx
  src/styles/pages/page.style.tsx
Labels: 개선, 공통

#127 add updated api - #124
  src/api/services/Meeting.type.ts
  src/api/services/MeetingAPI.ts
  src/api/services/types.ts
  src/api/types/meeting.type.ts
  src/app/applicationInfo/page.tsx
  src/app/apply/branching/page.tsx
  src/app/page.tsx
  src/components/footer/Footer.tsx
  src/components/modal/bottomSheet/BottomSheet.tsx
  src/components/molecules/resultBox/ResultBox.tsx
  src/components/molecules/teamStatusBox/TeamStatusBox.tsx
  src/page/common/applyMyInfoStep/FirstPage.tsx
  src/page/groupLeader/SecondStep/FirstPage.tsx
  src/page/groupLeader/SecondStep/SecondPage.tsx
  src/page/groupMember/SecondStep/FirstPage.tsx
  src/page/personal/FirstStep/FourthPage.tsx
  src/page/personal/ThirdStep/SecondPage.tsx
  src/store/feature/common/commonReducer.ts
  src/store/feature/meetingType/groupReducer.ts
  src/store/feature/meetingType/personalReducer.ts
Labels: 개선, 소개팅, 미팅, 공통

#128 unable return meeting type - #118
  src/app/apply/branching/page.tsx
  src/app/apply/page.tsx
  src/app/page.tsx
  src/components/footer/Footer.tsx
  src/components/modal/toast/Toast.tsx
Labels: 개선, 공통

#130 feat: 팅 이름 설정시 2자리 이상이 되도록 로직 추가 - #122
  src/components/footer/Footer.tsx
  src/page/groupLeader/SecondStep/FirstPage.tsx
Labels: 개선, 미팅

#131 feat: 배포 전 마지막 수정 일부 구현 - #129
  src/api/core/index.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/molecules/resultBox/ResultBox.tsx
  src/styles/pages/page.style.tsx
Labels: 개선, 소개팅, 미팅, 공통

#132 feat: final change - #129
  src/api/types/meeting.type.ts
  src/app/applicationInfo/page.tsx
  src/app/page.tsx
  src/page/common/ConfirmStep.tsx
  src/utils/index.ts
Labels: 개선, 공통

#134 Feat/ 133-binaryToInformation 최종 수정
  src/constants/departments.ts
  src/page/common/ConfirmStep.tsx
  src/types/information.type.ts
  src/utils/binary/informationToBinary.ts
Labels: 개선, 공통

#137 feat: binary to information - #135
  src/app/applicationInfo/page.tsx
  src/components/footer/Footer.tsx
  src/page/common/ConfirmStep.tsx
  src/page/groupLeader/SecondStep/SecondPage.tsx
  src/page/personal/ThirdStep/FirstPage.tsx
  src/utils/binary/binaryToInfomation.ts
  src/utils/binary/informationToBinary.ts
  src/utils/index.ts
Labels: 개선, 소개팅, 미팅, 공통

#148 fix: bug fix - #139
  src/components/footer/Footer.tsx
Labels: 개선, 미팅

#153 feat: 신청 연장 관련 문구 수정 - #152
  src/app/applicationInfo/page.tsx
  src/app/apply/complete/page.tsx
  src/app/page.tsx
  src/components/modal/toast/Toast.tsx
Labels: 개선, 공통

#154 feat: apply extension - #152
  src/app/page.tsx
Labels: 개선

#155 fix: bug fix - #139
  src/components/header/mainHeader/MainHeader.tsx
Labels: 개선, 공통
